shortener/urls.py
from django.urls import re_path, path
from .views import index, redirect_original, shorting_url, register, login, logout


app_name = 'shortener'

urlpatterns = [
    # re_path('', index, name='home'),
    re_path('index', index, name='home'),
    path('redirect_original/<slug:shorted_url>/', redirect_original, name='redirectoriginal'),
    re_path('shorting_url', shorting_url, name='shorting_url'),
    re_path('register', register, name='register'),
    re_path('login', login, name='login'),
    re_path('logout', logout, name='logout'),
]

urlshortener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path(r'', include('shortener.urls', namespace='shortenersite')),
]

shortener/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

from .managers import CustomUserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username = models.TextField(max_length=20, default='Unknown')
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return str(self.email)


class Url(models.Model):
    default_url = models.URLField()
    shorted_url = models.SlugField(max_length=6)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return str(self.id)

shortener/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import User


class UserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'username')


class UserAuthenticateForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ('email', 'password')

shortener/views.py
from sys import prefix
from django.shortcuts import render, get_object_or_404, redirect
import random, string, json
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.contrib.auth import login as login_user
from django.contrib.auth import logout as logout_user
from django.contrib.auth import authenticate
from django.contrib import messages
from django.views.decorators.csrf import csrf_protect
from .models import Url, User
from .forms import UserCreationForm, UserAuthenticateForm


@csrf_protect
def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login_user(request, user)
            messages.success(request, "Registration successful." )
            return redirect("shortener:home")
        else:
            messages.error(request, "Unsuccessful registration. Invalid information.")
    form = UserCreationForm()
    return render(request, "shortener/register.html", context={"register_form" : form})

@csrf_protect
def login(request):
    if request.method == "POST":
        form = UserAuthenticateForm(request, data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=email, password=password)
            if user is not None:
                login_user(request, user)
                messages.info(request, f"You are now logged in as {email}.")
                return redirect("shortener:home")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = UserAuthenticateForm()
    return render(request, "shortener/login.html", context={"login_form" : form})

def logout(request):
	logout_user(request)
	messages.info(request, "You have successfully logged out.") 
	return redirect("shortener:home")

@csrf_protect
def index(request):
    urls = Url.objects.all()
    try:
        previous_urls = Url.objects.filter(user=request.user)
    except:
        previous_urls = None
    prefix = settings.SITE_URL
    return render(request, 'shortener/index.html', context={'urls' : urls, 'prefix': prefix, 'previous_urls' : previous_urls})

def redirect_original(request, shorted_url):
    url = get_object_or_404(Url, shorted_url=shorted_url)
    return HttpResponseRedirect(url.default_url)

def shorting_url(request):
    url = request.POST.get("url", '')
    if not (url == ''):
        shorted_url = create_short_url()
        try:
            user = request.user
        except:
            user = None
        b = Url(default_url=url, shorted_url=shorted_url, user=user)
        b.save()
        response_data = {}
        response_data['url'] = settings.SITE_URL + "/" + shorted_url
        return HttpResponse(json.dumps(response_data),  content_type="application/json")
    return HttpResponse(json.dumps({"error": "error occurs"}), content_type="application/json")

def create_short_url():
    length = 6
    char = string.ascii_uppercase + string.digits + string.ascii_lowercase
    while True:
        shorted_url = ''.join(random.choice(char) for x in range(length))
        try:
            temp = Url.objects.get(pk=shorted_url)
        except:
            return shorted_url

shortener/templates/shortener/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}URL shortener{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'shortener/css/custom.css' %}" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<script type="text/javascript">
 $(function() {
 $('#submitButton').click(function() {
 $.ajax({
 type: "POST",
 url: "/shorting_url/",
 data: {
 'url' : $('#url').val(),
 'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val()
 },
 success: returnSuccess,
 dataType: 'json'
 });
 });
});

function returnSuccess(data, textStatus, jqXHR) {
 if(data.url) {
 $('#url-result').text(data.url);
 $('#url').val("");
 } else {
 $('#url-result').text("Do not submit blank.");
 }

}
</script>
<body>
    <div id="wrap">
    <header>
        <h1><a href="{% url 'shortener:home' %}">URL Shortner</a><small> Shorten the URL</small></h1>
        {% if user.is_authenticated %}
        <p>Logged as {{ user.username }} </p>
        <a href="{% url 'shortener:logout' %}">Logout</a>
        {% else %}
        <p>New to this site?<a href="{% url 'shortener:register' %}"> Sign Up!</a> or <a href="{% url 'shortener:login' %}"> Log In</a> if u have an account.</p>
        {% endif %}
    </header>

        <div id="content">
        {% block content %}

        {% endblock %}
        </div>
    </div>
</body>
</html>

shortener/templates/shortener/index.html
{% extends "shortener/base.html" %}

{% block title %}URL shortener{% endblock %}

{% block content %}

<div class="panel panel-default">
    <div class="panel-body">
        <div class="col-sm-9">
            <input type="text" name="url" id="url" class="form-control input-sm" placeholder="http://example.com/verylongurl..." />
        </div>
        <div class="col-sm-3">
        {% csrf_token %}
            <button id="submitButton" class="btn btn-primary">Make it shorter</button></p>
        </div>
 </div>
<div class="panel-footer"><span id="url-result">Enter the URL above and click submit!</span></div>
</div>

<div style="float: left;">
<p>All results</p>
{% for data in urls %}

<table class='table' style="float: left;">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Shorted URL</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">{{ data.id }}</th>
        <td><a href="{% url 'shortener:redirectoriginal' shorted_url=data.shorted_url %}">{{ prefix|add:'/'|add:data.shorted_url}}</a></td>
      </tr>
    </tbody>
  </table>

{% endfor %}

{% if user.is_authenticated %}
<p>Previous results</p>
{% for data in previous_urls %}
<table class='table' style="float: left;">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Shorted URL</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">{{ data.id }}</th>
        <td><a href="{% url 'shortener:redirectoriginal' shorted_url=data.shorted_url %}">{{ prefix|add:'/'|add:data.shorted_url}}</a></td>
      </tr>
    </tbody>
  </table>
</div>
{% endfor %}
{% endif %}
{% endblock %}

shortener/templates/shortener/login.html
{% extends "shortener/base.html" %}

{% block content %}      

<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form }}
    <button class="btn btn-primary" type="submit">Login</button>
    <p class="text">Don't have an account? <a href={% url 'shortener:register' %}>Create an account!</a></p>
  </form>
</div>

{% endblock %}

shortener/templates/shortener/register.html
{% extends "shortener/base.html" %}

{% block content %}      

<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form }}                    
		<button class="btn btn-primary" type="submit">Register</button>
        <p class="text"> If you already have an account, <a href={% url 'shortener:login' %}>Log In</a> instead.</p>
	</form>
</div>

{% endblock %}